sudo: required
services: 
  - docker

before_install:
  - docker build -t khoaln6/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -t khoaln6/react-test npm test -- --coverage

after_success:
  - docker build -t khoaln6/multi-client ./client
  - docker build -t khoaln6/multi-nginx ./nginx
  - docker build -t khoaln6/multi-server ./server
  - docker build -t khoaln6/multi-woker ./worker

  #Login to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push them to docker hub
  - docker push khoaln6/multi-client
  - docker push khoaln6/multi-nginx
  - docker push khoaln6/multi-server
  - docker push khoaln6/multi-worker

